pipeline {
    agent any
    
    environment {
        DB_CREDS = credentials('postgres_db_credentials')
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Install Dependencies') {
            steps {
                dir('PyTest DQ Framework') {
                    sh '''
                    # Створюємо віртуальне оточення
                    python3 -m venv venv
                    # Встановлюємо пакети всередину venv
                    ./venv/bin/pip install --upgrade pip
                    ./venv/bin/pip install -r requirements.txt
                    '''
                }
            }
        }
        
        stage('Run Data Quality Tests') {
            steps {
                dir('PyTest DQ Framework') {
                    sh """
                    # Створюємо папку для звіту заздалегідь
                    mkdir -p html_report
                    
                    # Запускаємо pytest через venv
                    ./venv/bin/pytest tests -m "parquet_data" \
                    --db_host="host.containers.internal" \
                    --db_port="5432" \
                    --db_name="mydatabase" \
                    --db_user="${DB_CREDS_USR}" \
                    --db_password="${DB_CREDS_PSW}" \
                    --html=html_report/report.html --self-contained-html || true
                    """
                }
            }
        }
    }
    
    post {
        always {
            // Тепер папка html_report точно існує, тому помилки не буде
            publishHTML(target: [
                allowMissing: true, // Змінив на true, щоб білд не падав, якщо тести взагалі не запустилися
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'PyTest DQ Framework/html_report',
                reportFiles: 'report.html',
                reportName: 'Data Quality Report'
            ])
        }
    }
}