[pytest]
python_files = test_*

markers =
    validate_csv: tests for validation of the CSV file
    unmarked: automated set marker for test without markers

addopts = --html=report.html --self-contained-html